<a href="https://colab.research.google.com/github/mahima0811gupta/statisticML/blob/main/Matrixoperation1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating a M atrix using numpy

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)


[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:

matrix_2.shape

(3, 3)

Creating Matrix with random values

In [ ]:
random_matrix=np.random.rand(2,3)
print(random_matrix)

[[0.37336368 0.34486608 0.6081649 ]
 [0.35681061 0.74658168 0.00325938]]


In [ ]:
random_integer_matrix=np.random.randint(100,size=(4,4))
print(random_integer_matrix)

[[ 0 36 33 81]
 [42 21 39 84]
 [ 7  1 82 58]
 [77 77 39 10]]


In [ ]:
matrix_3=np.ones((3,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3=np.ones((3,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
null_matrix=np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_matrix=np.zeros((4,4),dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:

#identity matrix
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


transpose matrix

In [ ]:

a=np.random.randint(100,size=(3,3))
print(a)



[[52 10  8]
 [50 66 66]
 [50 26 80]]


In [ ]:
transpose_a=np.transpose(a)
print(transpose_a)

[[52 50 50]
 [10 66 26]
 [ 8 66 80]]
