<a href="https://colab.research.google.com/github/mahima0811gupta/statisticML/blob/main/matrixoperation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Addition

In [ ]:
A=np.array([[2,3],[4,5]])
B=np.array([[5,3],[5,6]])

sum=A+B
print(sum)


[[ 7  6]
 [ 9 11]]


In [ ]:
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,3))
sum=np.add(matrix_1,matrix_2)
print(sum)

[[ 80  49 102]
 [ 69  42  65]
 [157 126  74]]


Substraction

In [ ]:
A=np.array([[4,7],[6,5]])
B=np.array([[2,7],[1,5]])
sub=A-B
print(sub)


[[2 0]
 [5 0]]


In [ ]:
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,3))
subtract=np.subtract(matrix_1,matrix_2)
print(subtract)

[[ 46  31  48]
 [-91   3 -18]
 [ 17  -8 -68]]


Multiplying by a matrix by a scalar

In [ ]:
x = 5
y = np.random.randint(10, size=(4,4))
print(y)

[[3 9 9 7]
 [9 9 9 3]
 [5 5 3 6]
 [2 0 4 1]]


In [ ]:
product = np.multiply(x,y)
print(product)

[[15 45 45 35]
 [45 45 45 15]
 [25 25 15 30]
 [10  0 20  5]]


Multiplying 2 Matrices


In [ ]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))
print(matrix_3)
print(matrix_4)
product = np.dot(matrix_3, matrix_4)
print(product)


[[4 2 3]
 [1 4 4]
 [3 3 4]]
[[2 2 4 0]
 [1 2 4 1]
 [2 2 0 1]]
[[16 18 24  5]
 [14 18 20  8]
 [17 20 24  7]]
